# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Test compile for Arduino
      uses: ArminJo/arduino-test-compile@v2.2.0
      with:
        # Version of arduino-cli to use when builing. Current (3/2020) one is 0.9.0.
        cli-version: # optional, default is latest
        # Comma sepatated list of patterns or filenames (without path) of the sketch(es) to test compile. Useful if the sketch is a *.cpp or *.c file or only one sketch in the repository should be compiled.
        sketch-names: # optional, default is *.ino
        # Fully Qualified Board Name of the Arduino board. You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace.
        arduino-board-fqbn: # optional, default is arduino:avr:uno
        # The platform specifier, if you require a fixed version like arduino:avr@1.8.2 or do not want the specifier derived from the 2 first elements of the arduino-board-fqbn
        arduino-platform: # optional, default is 
        # The platform URL for the required board description if arduino-board-fqbn does not start with "arduino:".
        platform-url: # optional, default is 
        # Comma separated list of arduino library names required for compiling the sketches / examples for this board.
        required-libraries: # optional, default is 
        # Comma or space separated list of significant prefixes of all sketches / examples to be excluded in the build for this board.
        examples-exclude: # optional, default is 
        # Build parameter like -DDEBUG for each example specified or for all examples, if example name is "All". In json format.
        For example: examples-build-properties: '{ "WhistleSwitch": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }'
        examples-build-properties: # optional, default is 
        # If set to "true" she action logs verbose compile output even during successful builds
        debug: # optional, default is 
